### ISSUE TITLE
Demonstration data error 

### ISSUE THREAD

**Issue by wwh199459** [liupei101/TFDeepSurv#12]
Hello, I reported an error while running the TFDeepSurv demo data. Do you know what caused it? Thank you for your guidance. 
![捕获2](https://user-images.githubusercontent.com/63087241/131062794-58587dc2-3a1e-4dc5-917b-ba4e9d1d6642.JPG)

**Comment by liupei101** [comment]
You need to check syntax.

It is not related to this repo. Closed.

**Comment by liupei101** [comment]
You need to check syntax.

It is not related to this repo. Closed.
