### ISSUE TITLE
TFDeepSurv package on medical images ?

### ISSUE THREAD

**Issue by eballot21** [liupei101/TFDeepSurv#13]
@liupei101 Thank you so much for the package.

Could you please tell is it possible to use TFDeepSurv package on medical images ?
Where can the convolution layers be introduced? 

Thank you!

**Comment by liupei101** [comment]
Thx for your feedback.

TFDeepSurv cannot directly be utilized for medical iamges. It is developed for a feature representation. If you want to use this package on your own images, maybe you can try to 
- add some conv modules in the model to extract the feature of image;
- firstly obtain representations of images and then input it to TFDeepSurv.

Any survival prediction related models can be built upon TFDeepSurv. All you need is to deal with the input data (tables, images or 3D objects).
