### ISSUE TITLE
Why the parameters optimized by Bayesian parameters are not optimal？

### ISSUE THREAD

**Issue by DWang12138** [liupei101/TFDeepSurv#18]
The training set is adjusted according to the proportion of 0.8, and the parameters after Bayesian parameter optimization are not optimal for the whole training set. Do you know how to solve this problem?

**Comment by liupei101** [comment]
Bayesian parameter optimization cannot always find the optimal solution. It's just utilized to help us obtain some model hyper-parameters that are expected to be good (or not too bad) for fitting the desired model.
